comments:
  AbsentOrWrongFileLicense:
    active: true

  DeprecatedBlockTag:
    active: true

  OutdatedDocumentation:
    active: true

  UndocumentedPublicClass:
    active: true
    excludes: [ '**/demo/**', '**/*Test.kt' ]
    ignoreDefaultCompanionObject: true

  UndocumentedPublicFunction:
    active: true
    excludes: [ '**/demo/**', '**/*Test.kt' ]

  UndocumentedPublicProperty:
    active: true
    excludes: [ '**/demo/**', '**/*Test.kt' ]

complexity:
  LongParameterList:
    ignoreAnnotated: [ 'Composable' ]

  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Preview' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  MagicNumber:
    ignoreAnnotated: [ 'Composable' ]

  UnusedPrivateFunction:
    ignoreAnnotated: [ 'Preview', 'PreviewLightDark' ]
